Models/Class.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ejercicio.Models
{
    public class Class
    {
        public int id { get; set; }
        public string nombre1 { get; set; }
        public string nombre2 { get; set; }
        public string apellido1 { get; set; }
        public string apellido2 { get; set; }

        public int telefono { get; set; }
        public string direccion { get; set; }
        public string correo { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace ejercicio.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/ClassesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ejercicio.Data;
using ejercicio.Models;

namespace ejercicio.Controllers
{
    public class ClassesController : Controller
    {
        private readonly ejercicioContext _context;

        public ClassesController(ejercicioContext context)
        {
            _context = context;
        }

        // GET: Classes
        public async Task<IActionResult> Index()
        {
            return View(await _context.Class.ToListAsync());
        }

        // GET: Classes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @class = await _context.Class
                .FirstOrDefaultAsync(m => m.id == id);
            if (@class == null)
            {
                return NotFound();
            }

            return View(@class);
        }

        // GET: Classes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Classes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,nombre1,nombre2,apellido1,apellido2,telefono,direccion,correo")] Class @class)
        {
            if (ModelState.IsValid)
            {
                _context.Add(@class);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(@class);
        }

        // GET: Classes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @class = await _context.Class.FindAsync(id);
            if (@class == null)
            {
                return NotFound();
            }
            return View(@class);
        }

        // POST: Classes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,nombre1,nombre2,apellido1,apellido2,telefono,direccion,correo")] Class @class)
        {
            if (id != @class.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(@class);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClassExists(@class.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(@class);
        }

        // GET: Classes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @class = await _context.Class
                .FirstOrDefaultAsync(m => m.id == id);
            if (@class == null)
            {
                return NotFound();
            }

            return View(@class);
        }

        // POST: Classes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var @class = await _context.Class.FindAsync(id);
            _context.Class.Remove(@class);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClassExists(int id)
        {
            return _context.Class.Any(e => e.id == id);
        }
    }
}

Controllers/HomeController.cs
using ejercicio.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ejercicio.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Classes/Create.cshtml
@model ejercicio.Models.Class

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Class</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="nombre1" class="control-label"></label>
                <input asp-for="nombre1" class="form-control" />
                <span asp-validation-for="nombre1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="nombre2" class="control-label"></label>
                <input asp-for="nombre2" class="form-control" />
                <span asp-validation-for="nombre2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="apellido1" class="control-label"></label>
                <input asp-for="apellido1" class="form-control" />
                <span asp-validation-for="apellido1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="apellido2" class="control-label"></label>
                <input asp-for="apellido2" class="form-control" />
                <span asp-validation-for="apellido2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="telefono" class="control-label"></label>
                <input asp-for="telefono" class="form-control" />
                <span asp-validation-for="telefono" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="direccion" class="control-label"></label>
                <input asp-for="direccion" class="form-control" />
                <span asp-validation-for="direccion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="correo" class="control-label"></label>
                <input asp-for="correo" class="form-control" />
                <span asp-validation-for="correo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Classes/Delete.cshtml
@model ejercicio.Models.Class

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Class</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nombre1)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nombre1)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nombre2)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nombre2)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.apellido1)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.apellido1)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.apellido2)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.apellido2)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.telefono)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.telefono)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.direccion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.direccion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.correo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.correo)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Classes/Details.cshtml
@model ejercicio.Models.Class

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Class</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nombre1)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nombre1)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nombre2)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nombre2)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.apellido1)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.apellido1)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.apellido2)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.apellido2)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.telefono)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.telefono)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.direccion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.direccion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.correo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.correo)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Classes/Edit.cshtml
@model ejercicio.Models.Class

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Class</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id" />
            <div class="form-group">
                <label asp-for="nombre1" class="control-label"></label>
                <input asp-for="nombre1" class="form-control" />
                <span asp-validation-for="nombre1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="nombre2" class="control-label"></label>
                <input asp-for="nombre2" class="form-control" />
                <span asp-validation-for="nombre2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="apellido1" class="control-label"></label>
                <input asp-for="apellido1" class="form-control" />
                <span asp-validation-for="apellido1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="apellido2" class="control-label"></label>
                <input asp-for="apellido2" class="form-control" />
                <span asp-validation-for="apellido2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="telefono" class="control-label"></label>
                <input asp-for="telefono" class="form-control" />
                <span asp-validation-for="telefono" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="direccion" class="control-label"></label>
                <input asp-for="direccion" class="form-control" />
                <span asp-validation-for="direccion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="correo" class="control-label"></label>
                <input asp-for="correo" class="form-control" />
                <span asp-validation-for="correo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Classes/Index.cshtml
@model IEnumerable<ejercicio.Models.Class>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.nombre1)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.nombre2)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.apellido1)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.apellido2)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.telefono)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.direccion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.correo)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.nombre1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.nombre2)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.apellido1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.apellido2)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.telefono)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.direccion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.correo)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ejercicio</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ejercicio</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Classes" asp-action="Index">Registro</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ejercicio - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>